app/config/routes.rb
App::Application.routes.draw do
  resources :users
  resources :deals
  resources :sessions, only: [:new, :create, :destroy]
  resources :purchases, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  root to: 'static_pages#home'

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
end

app/app/models/deal.rb
include ActionView::Helpers::TextHelper

class Deal < ActiveRecord::Base
  attr_accessible :purchaser_bonus_points, :purchaser_id, :receiver_id, :points_for_distribution, :used
  belongs_to :purchaser, class_name: "User"
  belongs_to :receiver, class_name: "User"
  default_scope order: 'deals.created_at DESC'

   def to_s_sender
    "send " + pluralize(points_for_distribution, 'point') + " to a friend, and get extra " + pluralize(purchaser_bonus_points, 'point') + "."
   end

   def to_s_receiver
    "got " + pluralize(points_for_distribution, 'point') + " from " + User.find(purchaser_id).name
   end
end

app/app/models/purchase.rb
class Purchase < ActiveRecord::Base
  attr_accessible :new_points, :original_price, :price_after_discount, :used_points, :user_id
  belongs_to :user
  validates :user_id, presence: true  
  validate :original_price_value

  default_scope order: 'purchases.created_at DESC'

  def to_s
    "original price: " + original_price.to_s + " ,after discount: " + price_after_discount.to_s + " ,used points: " + used_points.to_s + " ,new points: " + new_points.to_s + " , "
   end

   private

   def original_price_value
	   	if original_price < 20
	   		errors.add(:original_price, " is out of range")
	   	end
   end
end

app/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name # TODO read only
  has_many :purchases , dependent: :destroy
  has_many :outgoing_deals, foreign_key: "purchaser_id", class_name: "Deal", dependent: :destroy
  has_many :incoming_deals, foreign_key: "receiver_id", class_name: "Deal", dependent: :destroy

  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }, uniqueness: true


 def points
      total = 0
      incoming_deals.each do |d|
          if !d.used
            total += d.points_for_distribution
            d.used=true
            d.save
          end
      end

      outgoing_deals.each do |d|
         if d.used
            total += d.purchaser_bonus_points
            User.find(d.purchaser_id).outgoing_deals.delete(d)
            d.destroy
            d.save
        end
      end
    return total
  end

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper

  # Force signout to prevent CSRF attacks
  def handle_unverified_request
    sign_out
    super
  end
end

app/app/controllers/deals_controller.rb
class DealsController < ApplicationController

  def edit
  	@deal = Deal.find(params[:id])
  end

 def update
    @deal = Deal.find(params[:id])
    if @deal.update_attributes(params[:deal])
      flash[:success] = "Deal assigned"
      redirect_to User.find(@deal.purchaser_id)
    else
      render 'edit'
    end
  end
end

app/app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController

  def index
  end

  def create
  	@user = User.find(params[:purchase][:user_id])
    @original_price  = params[:purchase][:original_price].to_i
    @used_points = @user.points
    @price_after_discount =  @original_price * 0.9 + ( @original_price * 0.1 ) / ( @used_points + 1 )
    @new_points = @original_price / 10
    @deal = @user.outgoing_deals.build(purchaser_bonus_points: @new_points - 1, points_for_distribution: @new_points, used: false)
  	@purchase = @user.purchases.build(original_price: @original_price, used_points: @used_points, price_after_discount: @price_after_discount, new_points: @new_points)
    if @purchase.save &&  @deal.save
      flash[:success] = "purchase created!"
      redirect_to user_path(@user)
    else
       flash[:error] = "purchase failed! " +@purchase.errors.full_messages.to_s + @deal.errors.full_messages.to_s
        redirect_to users_path
    end
  end

  def destroy
  end
end

app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_name(params[:session][:name])
    if user # && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash.now[:error] = 'Invalid user'
      render 'new'
    end
  end

   def destroy
    sign_out
    redirect_to root_url
  end
end

app/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def help
  end

  def about
  end
end

app/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @purchases = @user.purchases
    @outgoing_deals = @user.outgoing_deals
    @incoming_deals = @user.incoming_deals
  end

  def new
  	@user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def index
    @users = User.all
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end
end

app/app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.       # Documentation comment
  def full_title(page_title)                          # Method definition
    base_title = "Sample App"  # Variable assignment
    if page_title.empty?                              # Boolean test
      base_title                                      # Implicit return
    else
      "#{base_title} | #{page_title}"                 # String interpolation
    end
  end

 
end

app/app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  
end

app/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/app/helpers/users_helper.rb
module UsersHelper
end

app/app/views/deals/_deal.html.erb
<li>
 	<% if deal.purchaser_id==@user.id %>
		<span class="string"><%= deal.to_s_sender %>
	    <% if deal.receiver_id.nil? && !deal.used %>
			 <%= form_for(deal) do |f| %>
			  <%= f.label "Select User", class: "span2" %>
			  <%= f.select :receiver_id, options_for_select(User.all.reject{|a| a.id==deal.purchaser_id}.collect{ |u| [u.name , u.id]}) %>
		      <%= f.submit "Send", class: "btn btn-small btn-primary" %>
		    <% end %>

		<% elsif !deal.used  %>
			 <%= " sent to " + User.find(deal.receiver_id).name  %>	 
		<% else %>
			<%= "Deal has been applied! You have received " + pluralize(deal.purchaser_bonus_points, 'point') + "."%>	 	 
	    <% end %>
	  </span>
   <% else %>
    	<% if !deal.used %>
   			<span class="string"><%= deal.to_s_receiver %></span>
   		<% end %>
   <% end %>
</li>

app/app/views/deals/edit.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@deal) do |f| %>
	  <%= f.select :receiver_id, options_for_select(User.all.reject{|a| a.id==@deal.purchaser_id}.collect{ |u| [u.name , u.id]}) %>
      <%= f.submit "Send", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
    </ul>
  </nav>
</footer>

app/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "sample app", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "Help",    help_path %></li>
          <li><%= link_to "Users", users_path %></li>
          <% if signed_in? %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
 <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/app/views/purchases/_purchase.html.erb
<li>
  <span class="purchase"><%= purchase.to_s %></span>
  <span class="timestamp">
    <%= time_ago_in_words(purchase.created_at) %> ago.
  </span>
</li>

app/app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
  about
</p>

app/app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  help
</p>

app/app/views/static_pages/home.html.erb
 <div class="center hero-unit">
  <h1>Welcome to the Sample App</h1>

  <h2>
    This is the home page for the sample application.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

app/app/views/users/index.html.erb
<% provide(:title, 'All users') %>

<h1>All users</h1>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
       | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
       | <%= form_for(user.purchases.build(user_id: user.id)) do |f| %>
			   <%= f.hidden_field :user_id %>
			   <%= f.label :price , class: "span1"%>
	    	<%= f.number_field :original_price , class: "span4"%>
		  	<%= f.submit "Purchase", class: "btn btn-small btn-primary" %>
	   	 <% end %>                                                  
    </li>
  <% end %>
</ul>

app/app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= @user.name %>
      </h1>
    </section>
  </aside>

  <div class="span9">
    <% if @user.incoming_deals.any? %>
      <h3>incoming_deals (<%= @user.incoming_deals.count %>)</h3>
      <ol class="deals">
        <%= render @incoming_deals %>
      </ol>
    <% end %>
  </div>
  <div class="span9">
    <% if @user.outgoing_deals.any? %>
      <h3>outgoing_deals (<%= @user.outgoing_deals.count %>)</h3>
      <ol class="deals">
        <%= render @outgoing_deals %>
      </ol>
    <% end %>
  </div>
  <div class="span20">
    <% if @user.purchases.any? %>
      <h3>Purchases (<%= @user.purchases.count %>)</h3>
      <ol class="purchases">
        <%= render @purchases %>
      </ol>
    <% end %>
  </div>
</div>